// SPDX-FileCopyrightText : © 2026 Galvanized Logic Inc.
// SPDX-License-Identifier: MIT

package main

// egen.go is a vulkan vk.xml specification parser based on a
// (very rough, partial) golang port of the official pythyon spec
// parser scripts. See: https://github.com/KhronosGroup/Vulkan-Docs +
// - scripts/generator.py
// - scripts/cgenerator.py

import (
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strconv"
	"strings"

	// golang xml parsing similar to python etree.
	"github.com/beevik/etree" // godoc: https://pkg.go.dev/github.com/beevik/etree
)

// goTypes maps the vulkan spec types to the equivalent go type.
var goTypes = map[string]string{
	"char":     "byte",
	"int32_t":  "int32",
	"int64_t":  "int64",
	"uint8_t":  "uint8",
	"uint16_t": "uint16",
	"uint32_t": "uint32",
	"uint64_t": "uint64",
	"size_t":   "uintptr",
	"float":    "float32",
	"double":   "float64",
	"void":     "unsafe.Pointer",
	"VkBool32": "bool",

	// TODO find another way to fix. These are pNext var types which are usually void.
	"VkBaseInStructure":  "unsafe.Pointer",
	"VkBaseOutStructure": "unsafe.Pointer",

	// platform specific "windows" requires "golang.org/x/sys/windows"
	"HMONITOR":            "windows.Handle",
	"HANDLE":              "windows.Handle",
	"HINSTANCE":           "windows.Handle",
	"HWND":                "windows.HWND",
	"DWORD":               "uint32",
	"LPCWSTR":             "unsafe.Pointer",
	"SECURITY_ATTRIBUTES": "windows.SecurityAttributes",
}

func (gen *generator) mapType(ctype string) (gotype string) {
	if t, ok := goTypes[ctype]; ok {
		return t
	}
	return ctype
}

// goValues maps the vulkan spec values to the equivalent go type.
var goValues = map[string]string{
	"(~0U)":   "^uint32(0)",
	"(~0ULL)": "^uint64(0)",
	"(~1U)":   "^uint32(1)",
	"(~2U)":   "^uint32(2)",
}

// goVariables maps the vulkan spec variables when they conflict
// with golang reserved words.
var goVariables = map[string]string{
	"type":    "typ",
	"range":   "rang",
	"bool":    "b",
	"int32":   "typeInt32",
	"int64":   "typeInt64",
	"uint32":  "typeUint32",
	"uint64":  "typeUint64",
	"float32": "typeFloat32",
	"float64": "typeFloat64",
}

func (gen *generator) mapVariable(cvar string) (govar string) {
	if v, ok := goVariables[cvar]; ok {
		return v
	}
	return cvar
}

// ============================================================================

// generator captures output.
type generator struct {
	feature string // feature being generated.

	// output file
	// - "vk"       : platform independent consts, enums, types and structs.
	// - "vk_cgo"   : cgo commands
	// - "vk_sys"   : syscall commands
	// - "vk_*"     : platform features including cgo|syscall commands
	file string // output file.  "base" when there is no platform.

	// generator output by [file][section].
	out map[string]map[string]*strings.Builder
}

// newGenerator initializes the output buffers.
func newGenerator() *generator {
	gen := &generator{}
	gen.out = map[string]map[string]*strings.Builder{}

	// initialize the output buffers.
	files := []string{baseFile, cgoFile, syscallFile}
	for _, p := range platforms {
		files = append(files, "vk_"+p)
	}
	for _, f := range files {
		gen.out[f] = map[string]*strings.Builder{}
		for _, s := range sectionOrder {
			gen.out[f][s] = &strings.Builder{}
		}
		o := gen.out[f][includeSection]
		o.WriteString("// Code generated by vkgen from vk.xml. DO NOT EDIT.\n\n")
		switch f {
		case baseFile:
			o.WriteString("package vk\n\n")
			o.WriteString("import (\n")
			o.WriteString("	\"unsafe\"\n")
			o.WriteString("	\"fmt\"\n")
			o.WriteString(")\n")
		case cgoFile:
			o.WriteString("//go:build !windows\n\n")
			o.WriteString("package vk\n\n")
			o.WriteString("import (\n")
			o.WriteString("	\"unsafe\"\n")
			o.WriteString(")\n")
		case syscallFile:
			o.WriteString("//go:build windows\n\n")
			o.WriteString("package vk\n\n")
			o.WriteString("import (\n")
			o.WriteString("	\"syscall\"\n")
			o.WriteString("	\"unsafe\"\n")
			o.WriteString(")\n")
		case "vk_win32":
			o.WriteString("//go:build windows\n\n")
			o.WriteString("package vk\n\n")
			o.WriteString("import (\n")
			o.WriteString("	\"syscall\"\n")
			o.WriteString("	\"unsafe\"\n\n")
			o.WriteString("	\"golang.org/x/sys/windows\"\n")
			o.WriteString(")\n")
		case "vk_metal":
			o.WriteString("//go:build darwin || ios\n\n")
			o.WriteString("package vk\n\n")
			o.WriteString("import (\n")
			o.WriteString("	\"unsafe\"\n")
			o.WriteString(")\n")
		}
	}

	// add some base metal types
	if slices.Contains(platforms, "metal") {
		gen.file = "vk_metal"
		gen.write(basetypeSection, "\n")
		gen.write(basetypeSection, "type CAMetalLayer struct{}\n")
		gen.write(basetypeSection, "type IOSurfaceRef unsafe.Pointer\n")
		gen.write(basetypeSection, "type MTLBuffer_id unsafe.Pointer\n")
		gen.write(basetypeSection, "type MTLCommandQueue_id unsafe.Pointer\n")
		gen.write(basetypeSection, "type MTLDevice_id unsafe.Pointer\n")
		gen.write(basetypeSection, "type MTLSharedEvent_id unsafe.Pointer\n")
		gen.write(basetypeSection, "type MTLTexture_id unsafe.Pointer\n")
	}
	gen.file = baseFile
	return gen
}

// internal sections for document output.
const (
	includeSection  = "include"  //
	defineSection   = "define"   //
	basetypeSection = "basetype" //
	enumSection     = "enum"     //
	structSection   = "struct"   //
	bitmaskSection  = "bitmask"  //
	groupSection    = "group"    // enum's
	cmdSection      = "command"  //

	// output file names
	baseFile    = "vk"         // platform independent consts, enums, types and structs.
	cgoFile     = "vk_cgo"     // cgo commands
	syscallFile = "vk_syscall" // syscall commands
)

// ordered list of code output sections.
var sectionOrder = []string{
	includeSection,
	defineSection,
	basetypeSection,
	enumSection,
	bitmaskSection,
	groupSection,
	structSection,
	cmdSection,
}

// just hack the macros in rather than generating them from the spec.
// These depend on methods defined in static/static.go
var macrosMap = map[string]string{
	"VK_API_VERSION":             "var API_VERSION = MAKE_API_VERSION(0, 1, 0, 0)",
	"VK_API_VERSION_1_0":         "var API_VERSION_1_0 = MAKE_API_VERSION(0, 1, 0, 0)",
	"VK_API_VERSION_1_1":         "var API_VERSION_1_1 = MAKE_API_VERSION(0, 1, 1, 0)",
	"VK_API_VERSION_1_2":         "var API_VERSION_1_2 = MAKE_API_VERSION(0, 1, 2, 0)",
	"VK_API_VERSION_1_3":         "var API_VERSION_1_3 = MAKE_API_VERSION(0, 1, 3, 0)",
	"VK_API_VERSION_1_4":         "var API_VERSION_1_4 = MAKE_API_VERSION(0, 1, 4, 0)",
	"VK_API_VERSION_MAJOR":       "var API_VERSION_MAJOR = apiVersionMajor",
	"VK_API_VERSION_MINOR":       "var API_VERSION_MINOR = apiVersionMinor",
	"VK_API_VERSION_PATCH":       "var API_VERSION_PATCH = apiVersionPatch",
	"VK_API_VERSION_VARIANT":     "var API_VERSION_VARIANT = apiVersionVariant",
	"VK_HEADER_VERSION":          "var HEADER_VERSION = uint32(290)",
	"VK_HEADER_VERSION_COMPLETE": "var HEADER_VERSION_COMPLETE = MAKE_API_VERSION(0, 1, 4, HEADER_VERSION)",
	"VK_MAKE_API_VERSION":        "var MAKE_API_VERSION = makeApiVersion",
	"VK_MAKE_VERSION":            "var MAKE_VERSION = deprecatedMakeVersion",
	"VK_VERSION_MAJOR":           "var VERSION_MAJOR = deprecatedVersionMajor",
	"VK_VERSION_MINOR":           "var VERSION_MINOR = deprecatedVersionMinor",
	"VK_VERSION_PATCH":           "var VERSION_PATCH = deprecatedVersionPatch",
}

// Generate interface for a type
// - typeinfo - TypeInfo for a type
func (gen *generator) genType(info Info, typeName, alias string) {
	typeinfo := info.(*TypeInfo)
	typeElem := typeinfo.elem

	// Vulkan:
	// Determine the category of the type, and the type section to add
	// its definition to.
	category := typeElem.SelectAttrValue("category", "")

	// If the type is a struct type, generate it using the
	// special-purpose generator.
	if slices.Contains([]string{"struct", "union"}, category) {
		gen.genStruct(typeinfo, typeName, alias, category == "union")
	} else {
		if alias != "" {
			gen.write(basetypeSection, gen.deprecatedComment(typeElem)+"\n")
			// If the type is an alias, just emit a typedef declaration
			alias, _ = strings.CutPrefix(alias, "Vk")
			gen.write(basetypeSection, "type "+typeName+" "+alias+"\n")
		} else if category == "funcpointer" {
			gen.write(basetypeSection, gen.deprecatedComment(typeElem)+"\n")
			gen.write(basetypeSection, "type "+typeName+" unsafe.Pointer\n")
		} else {
			if category == defineSection {
				// map the c-macros defines.
				if outstr, ok := macrosMap[typeName]; ok {
					gen.write(includeSection, docLink("MACRO", typeName)+"\n")
					gen.write(includeSection, outstr+"\n")
				}
			} else if category == bitmaskSection {
				gen.write(category, gen.deprecatedComment(typeElem)+"\n")
				typ := typeElem.FindElement("type").Text()
				typ, _ = strings.CutPrefix(typ, "Vk")
				gen.write(category, docLink(bitmaskSection, typeName)+"\n")
				typeName, _ = strings.CutPrefix(typeName, "Vk")
				gen.write(category, "type "+typeName+" "+typ+"\n")
			} else if category == "handle" {
				gen.write(defineSection, gen.deprecatedComment(typeElem)+"\n")
				gen.write(defineSection, docLink("HANDLE", typeName)+"\n")
				typeName, _ = strings.CutPrefix(typeName, "Vk")
				handleType := typeElem.FindElement("type").Text()
				switch handleType {
				case "VK_DEFINE_HANDLE":
					gen.write(defineSection, "type "+typeName+" handle\n")
				case "VK_DEFINE_NON_DISPATCHABLE_HANDLE":
					gen.write(defineSection, "type "+typeName+" nonDispatchableHandle\n")
				default:
					slog.Error("expected a handle type", "name", typeName, "handle", handleType)
				}
			} else if category == basetypeSection {
				elemType := typeElem.FindElement("type")
				if elemType != nil {
					gen.write(defineSection, gen.deprecatedComment(typeElem)+"\n")
					typ := gen.mapType(elemType.Text())
					gen.write(defineSection, docLink("BaseType", typeName)+"\n")
					typeName, _ = strings.CutPrefix(typeName, "Vk")
					gen.write(defineSection, "type "+typeName+" "+typ+"\n")
				}
			} else if category == "include" {
				// the spec c-includes are ignored
			} else {
				// see what's left over, ie:
				//    slog.Debug("genType:TODO", "name", typeName)
				// which outputs following base types which are handled through mapping.
				//    name=uint32_t
				//    name=uint64_t
				//    name=int32_t
				//    name=void
				//    name=size_t
				//    name=char
				//    name=float
				//    name=uint8_t
			}
		}
	}
}

// Generate groups (e.g. C "enum" type).
// - groupinfo - GroupInfo for a group.
//
// These are concatenated together with other types.
//
// If alias is not None, it is the name of another group type
// which aliases this type; just generate that alias.
func (gen *generator) genGroup(info Info, groupName, alias string) {
	groupinfo := info.(*GroupInfo)

	// After either enumerated type or alias paths, add the declaration
	// to the appropriate section for the group being defined.
	groupType := groupinfo.elem.SelectAttrValue("type", "")
	section := "group"
	if groupType == "bitmask" {
		section = "bitmask"
	}

	// If the group name is aliased, just emit a typedef declaration
	// for the alias.
	if alias != "" {
		alias, _ = strings.CutPrefix(alias, "Vk")
		groupName, _ := strings.CutPrefix(groupName, "Vk")
		gen.write(section, docLink("aliasgroup", groupName)+"\n")
		gen.write(section, "type "+groupName+" = "+alias+"\n\n")
	} else {
		gen.buildEnumCDecl(section, false, groupinfo, groupName)
	}
}

// If an API element is marked deprecated, return a brief comment
// describing why.
// Otherwise, return an empty string.
//   - elem - Element of the API.
//     API name is determined depending on the element tag.
//   - indent - number of spaces to indent the comment
func (gen *generator) deprecatedComment(elem *etree.Element) string {
	reason := elem.SelectAttrValue("deprecated", "")
	if reason != "" {
		return "// deprecated: " + reason
	}
	return "" // This is almost always the path taken.
}

// Generate the C declaration for an enum
func (gen *generator) buildEnumCDecl(section string, expand bool, groupinfo *GroupInfo, groupName string) {
	groupElem := groupinfo.elem

	// Determine the required bit width for the enum group.
	// 32 is the default, which generates C enum types for the values.
	bitwidth := 32
	groupType := groupElem.SelectAttrValue("type", "")
	bitWidthAttr := groupElem.SelectAttrValue("bitwidth", "")

	// # Check for an explicitly defined bitwidth, which will override any defaults.
	if bitWidthAttr != "" {
		bitwidth, _ = strconv.Atoi(bitWidthAttr)
	}

	// Bitmask flags can be generated as either "static const uint{32,64}_t" values,
	// or as 32-bit C enums. 64-bit types must use uint64_t values.
	usebitmask := false
	isBitmask := groupType == "bitmask"
	if isBitmask && bitwidth > 32 {
		usebitmask = true
	}
	if usebitmask {
		gen.write(section, docLink("BITMASK64", groupName)+"\n")
		groupName, _ = strings.CutPrefix(groupName, "Vk")
		gen.buildEnumCDecl_BitmaskOrDefine(section, groupinfo, groupName, bitwidth)
	} else {

		// Prefix
		groupName, _ = strings.CutPrefix(groupName, "Vk")
		if isBitmask {
			gen.write(section, docLink("BITMASK32", groupName)+"\n")
			typedef := strings.Replace(groupName, "Bit", "", 1)
			gen.write(section, "type "+groupName+" = "+typedef+"\n")
		} else {
			gen.write(section, docLink("ENUM32", groupName)+"\n")
			gen.write(section, "type "+groupName+" int32\n")
		}

		// special handling to insert some code for the Result type
		if groupName == "Result" {
			gen.write(section, "\n    // Error implements the error interface\n")
			gen.write(section, "	func (r Result) Error() string { return fmt.Sprintf(\"%d\", r) }\n\n")

			// define "Result" SUCCESS as the golang nil error.
			gen.write(section, "	// Command completed successfully\n\n")
			gen.write(section, "	var SUCCESS error = nil // ie: the C zero return\n\n")
		}

		// Get a list of nested 'enum' tags.
		// Check for and report duplicates, and return a list with them removed.
		gen.write(section, "const (\n")
		enums := groupElem.FindElements("enum")
		enums = gen.checkDuplicateEnums(enums)
		for _, elem := range enums {
			strval := gen.enumToValue(elem)
			strval, _ = strings.CutPrefix(strval, "VK_")
			name := elem.SelectAttrValue("name", "")
			name, _ = strings.CutPrefix(name, "VK_")
			if groupName == "Result" && name == "SUCCESS" {
				continue // defined above
			}
			if strval != "" {
				gen.write(section, "   "+name+" "+groupName+" = "+strval+"\n")
			} else {
				slog.Error("buildEnumCDecl: no enum value", "enum", name)
			}
		}
		gen.write(section, ")\n\n")
	}
}

// Generate the C declaration for an "enum" that is actually a
// set of flag bits
func (gen *generator) buildEnumCDecl_BitmaskOrDefine(section string, groupinfo *GroupInfo, groupName string, bitwidth int) {
	groupElem := groupinfo.elem
	// groupName, _ = strings.CutPrefix(groupName, "Vk")
	flagTypeName := groupElem.SelectAttrValue("name", "")
	flagTypeName, _ = strings.CutPrefix(flagTypeName, "Vk")

	// Prefix
	gen.write(section, "type "+groupName)
	if bitwidth == 64 {
		gen.write(section, " uint64\n")
	} else {
		gen.write(section, " uint32\n")
	}
	gen.write(section, "const (\n")

	// Get a list of nested 'enum' tags.
	enums := groupElem.FindElements("enum")

	// Check for and report duplicates, and return a list with them removed.
	enums = gen.checkDuplicateEnums(enums)

	// Loop over the nested 'enum' tags.
	for _, elem := range enums {

		// Convert the value to an integer and use that to track min/max.
		// Values of form -(number) are accepted but nothing more complex.
		// Should catch exceptions here for more complex constructs. Not yet.
		strval := gen.enumToValue(elem)
		strval, _ = strings.CutPrefix(strval, "VK_")
		name := elem.SelectAttrValue("name", "")
		name, _ = strings.CutPrefix(name, "VK_")
		if strval != "" {
			gen.write(section, "   "+name+" "+flagTypeName+" = "+strval+"\n")
		} else {
			slog.Error("buildEnumCDecl_BitmaskOrDefine: no enum value", "enum", name)
		}
	}
	gen.write(section, ")\n\n")
}

// Check enumerated values for duplicates.
// -  enums - list of `<enum>` Elements
// returns the list with duplicates stripped
func (gen *generator) checkDuplicateEnums(enums []*etree.Element) (deduped []*etree.Element) {
	nameMap := map[string]bool{}
	stripped := []*etree.Element{}
	for _, elem := range enums {
		name := elem.SelectAttrValue("name", "")
		if _, ok := nameMap[name]; ok {
			slog.Info("ignoring duplicate enum", "name", name)
			continue // Do not add the duplicate to the returned list
		} else {
			nameMap[name] = true
			stripped = append(stripped, elem) // Add this enum to the list
		}
	}
	return stripped // Return the list
}

// Generate the declaration for a constant (a single <enum> value).
// - info - EnumInfo for an enum
// - name - enum name
//
// <enum> tags may specify their values in several ways, but are
// usually just integers.
func (gen *generator) genEnum(info Info, name, alias string) {
	// gen.write(enumSection, gen.deprecatedComment(info.element())+"\n")
	gen.buildConstantCDecl(info, name, alias)
}

// Generate the C declaration for a constant (a single <enum> value).
//
// <enum> tags may specify their values in several ways, but are
// usually just integers or floating-point numbers.
func (gen *generator) buildConstantCDecl(info Info, name, alias string) {
	enuminfo := info.(*EnumInfo)
	strval := gen.enumToValue(enuminfo.elem)
	strval, _ = strings.CutPrefix(strval, "VK_")
	if gv, ok := goValues[strval]; ok {
		strval = gv
	}
	name, _ = strings.CutPrefix(name, "VK_")
	if alias != "" {
		alias, _ = strings.CutPrefix(alias, "VK_")
		gen.write(enumSection, name+" = "+alias+"\n")
	} else {
		typeStr := gen.mapType(enuminfo.elem.SelectAttrValue("type", ""))
		strval, _ = strings.CutSuffix(strval, "F")
		strval, _ = strings.CutSuffix(strval, "f")
		gen.write(enumSection, ""+name+" "+typeStr+"="+strval+"\n")
	}
}

// Parse and convert an `<enum>` tag into a value.
func (gen *generator) enumToValue(elem *etree.Element) (val string) {
	if value := elem.SelectAttrValue("value", ""); value != "" {
		return value
	}
	if bitpos := elem.SelectAttrValue("bitpos", ""); bitpos != "" {
		return "1 << " + bitpos
	}
	if offsetStr := elem.SelectAttrValue("offset", ""); offsetStr != "" {

		// Obtain values in the mapping from the attributes
		extnumberStr := elem.SelectAttrValue("extnumber", "1")
		offset, _ := strconv.Atoi(offsetStr)
		extnumber, _ := strconv.Atoi(extnumberStr)
		enumNegative := false
		dir := elem.SelectAttrValue("dir", "")
		if dir != "" {
			enumNegative = true
		}

		// Now determine the actual enumerant value, as defined
		// in the "Layers and Extensions" appendix of the spec.
		// ie: value=1000000000+(extnumber−1)×1000+offset
		extBase := 1000000000
		extBlockSize := 1000
		numVal := extBase + (extnumber-1)*extBlockSize + offset
		if enumNegative {
			numVal *= -1
		}
		return strconv.Itoa(numVal)
	}
	if alias := elem.SelectAttrValue("alias", ""); alias != "" {
		return alias
	}
	return ""
}

// Generate interface for a C "struct" type.
func (gen *generator) genStruct(info Info, typeName, alias string, isUnion bool) {
	typeinfo := info.(*TypeInfo)
	typeElem := typeinfo.elem

	// The mixed-mode <member> tags may contain no-op <comment> tags.
	// It is convenient to remove them here where all output generators will benefit.
	for _, member := range typeElem.FindElements(".//member") {
		for _, comment := range member.FindElements("comment") {
			member.RemoveChild(comment)
		}
	}
	if alias != "" {
		alias, _ = strings.CutPrefix(alias, "Vk")
		gotype, _ := strings.CutPrefix(typeName, "Vk")
		gen.write(structSection, "type "+gotype+" "+alias+"\n")
		return
	}
	sinfo := &Struct{Name: typeName, Mems: []Member{}}
	sinfo.Ret = info.element().SelectAttrValue("returnedonly", "")
	sinfo.Doc = docLink("struct", typeName)
	sinfo.Comment = gen.deprecatedComment(typeElem)
	for _, member := range typeElem.FindElements(".//member") {
		smem := Member{}
		nameElem := member.FindElement("name")
		nameTail := nameElem.Tail()
		smem.Name = gen.mapVariable(nameElem.Text())

		// refine the member length information.
		smem.Len = member.SelectAttrValue("len", "")
		if strings.HasPrefix(smem.Len, "latexmath") {
			smem.Len = "" // FUTURE: maybe use latex length expressions.
		}
		if strings.Contains(smem.Len, "null-terminated") {
			smem.IsNullTerminated = true
		}
		if strings.Contains(smem.Len, ",null-terminated") {
			smem.Len = strings.Replace(smem.Len, ",null-terminated", "", 1)
		}
		if typeName == "VkDeviceCreateInfo" && smem.Name == "ppEnabledLayerNames" {
			// HACK: spec did not have a "len=" for this deprecated field.
			smem.Len = "enabledLayerCount"
		}

		smem.Value = member.SelectAttrValue("values", "")
		smem.Comment = gen.deprecatedComment(member)
		typeElem := member.FindElement("type")
		typeText := typeElem.Text()
		typeTail := typeElem.Tail()
		smem.Type = gen.mapType(typeText)
		if typeText == "VkBool32" {
			sinfo.RequiresConvert = true
		}
		enum := member.FindElement("enum")
		switch {
		case isUnion:
			if nameTail != "" {
				smem.Array = nameTail
			}
		case strings.HasPrefix(typeTail, "* "):
			smem.Ptr = "*"
			switch {
			case smem.Type == "unsafe.Pointer" && typeText == "void" && smem.Len == "":
				// void pointer
			case smem.Type == "byte" && strings.HasPrefix(typeTail, "* const*"):
				smem.IsStringSlice = true
				smem.Ptr = "**"
			case smem.Type == "byte" && typeText == "char" && smem.IsNullTerminated:
				smem.IsString = true
			case strings.HasSuffix(smem.Len, "Count"):
				// println(".... found array slice", smem.Len)
				// array with reference to count paramter. ... convert to slice.
			default:
				// standard pointer
				// println(smem.Name, smem.Type, "text", typeElem.Text(), "tail", typeElem.Tail(), "len", smem.Len)
			}
		case smem.Type == "byte" && enum != nil && smem.Len == "null-terminated":
			// fixed string array
			eval := enum.Text()
			eval, _ = strings.CutPrefix(eval, "VK_")
			smem.Array = "[" + eval + "]"
			smem.IsFixedString = true
		case nameTail != "" && enum == nil:
			smem.Array = nameTail // fixed array
		case enum != nil:
			// fixed array with size.
			eval := enum.Text()
			eval, _ = strings.CutPrefix(eval, "VK_")
			smem.Array = "[" + eval + "]"
		default:
			if smem.Name == "sType" {
				sinfo.RequiresConvert = true
			}
		}
		sinfo.Mems = append(sinfo.Mems, smem)
	}

	// some structures are excluded from slice mapping.
	// TODO figure out why and explain it here.
	excluded := []string{
		"VkPipelineCacheCreateInfo",
		"VkWriteDescriptorSetInlineUniformBlock",
		"VkPushConstantsInfo",
	}

	if slices.Contains(excluded, typeName) {
		slog.Debug("excluding struct from slice conversion", "type", typeName)
	} else {

		// look for counts + arrays members that can be converted to slices.
		for i, mem := range sinfo.Mems {
			for j, m2 := range sinfo.Mems {

				// found an slice candidate field that references count field as its length.
				if mem.Len == m2.Name && mem.Array == "" {
					if mem.Type == "unsafe.Pointer" {
						// println(sinfo.Name, mem.Name, "should not be slice")
						// only affects the VkSpecializationInfo struct
					} else {
						sinfo.Mems[i].IsSliceField = true
						sinfo.RequiresConvert = true
					}
				}

				// this member is referenced as the "Len" field in another member.
				// By convention this field ends with a "Count"
				if mem.Name == m2.Len && m2.Array == "" {
					if m2.Type == "unsafe.Pointer" {
						// println(sinfo.Name, mem.Name, "should not be slice counter")
						// only affects the VkSpecializationInfo struct
					} else {
						sinfo.Mems[i].IsSliceCounter = true
						sinfo.Mems[i].lenMems = append(sinfo.Mems[i].lenMems, &sinfo.Mems[j])

						// exception
						if sinfo.Name == "VkDescriptorSetLayoutBinding" && mem.Name == "descriptorCount" {
							sinfo.Mems[i].IsSliceCounter = false // dual use counter.
						}
					}
				}
			}
		}
	}
	gen.write(structSection, "")
	if isUnion {
		writeUnion(sinfo, gen.out[gen.file][structSection])
	} else {
		writeStruct(sinfo, gen.out[gen.file][structSection])
	}

	// track the structures
	allVkStructs[typeName] = sinfo
	if isUnion {
		allVkUnions[typeName] = sinfo
	}
}

// temp
var cout = &strings.Builder{}

// Generate interface for a command.
func (gen *generator) genCmd(info Info, cmdName, alias string) {
	cmdinfo, _ := info.(*CmdInfo)
	proto := cmdinfo.elem.FindElement("proto")
	cmd := &Cmd{Mems: []Member{}}
	cmd.Name = gen.mapVariable(proto.FindElement("name").Text())
	cmd.Type = gen.mapVariable(proto.FindElement("type").Text())
	cmd.Doc = docLink("cmd", cmd.Name)

	// output the command parameters.
	for _, param := range cmdinfo.elem.FindElements("param") {
		cmem := Member{}
		cmem.Name = gen.mapVariable(param.FindElement("name").Text())
		typeElem := param.FindElement("type")
		typeText := typeElem.Text()
		paramTail := param.Tail()
		paramText := param.Text()
		cmem.Type = gen.mapType(typeText)

		// refine the member length information.
		cmem.Len = param.SelectAttrValue("len", "")
		if cmem.Len != "" {
			// println("=-==== len", cmem.Len)
		}
		if strings.Contains(cmem.Len, "null-terminated") {
			// println("len is null terminated", cmem.Len)
			cmem.IsNullTerminated = true
		}
		if strings.Contains(cmem.Len, "->") {
			// Parameter is binding-allocated array populated by Vulkan;
			// length is embedded in a struct ie: pAllocateInfo->commandBufferCount
			cmem.IsBindingAllocatedArray = true
			cmem.Len = strings.Replace(cmem.Len, "->", ".", 1)
		}
		switch {
		case strings.HasPrefix(typeElem.Tail(), "** "):
			cmem.Ptr = "**"
			cmem.IsSingleReturn = true
		case strings.HasPrefix(typeElem.Tail(), "* "):
			cmem.Ptr = "*"
			isConst := strings.HasPrefix(paramTail, "const") || strings.HasPrefix(paramText, "const")
			isReturn := !isConst
			switch {
			case cmem.Type == "byte" && typeText == "char" && cmem.IsNullTerminated:
				cmem.IsString = true
			case cmem.Type == "unsafe.Pointer" && typeText == "void" && cmem.Ptr == "*":
				cmem.IsByteArray = true
			case isReturn:
				switch {
				case cmem.Len != "":
					cmem.IsSliceReturn = true
				default:
					cmem.IsSingleReturn = true
				}
			default:
				// standard pointers are handled in apigen
			}
		default:
			// standard vars are handled in apigen
		}
		cmd.Mems = append(cmd.Mems, cmem)
	}

	// look for counts + arrays members that can be converted to slices.
	for i, mem := range cmd.Mems {
		for j, m2 := range cmd.Mems {

			// found an slice candidate field that references count field as its length.
			if mem.Len == m2.Name {
				// println("slice", cmd.Name, mem.Name)
				cmd.Mems[i].IsSliceField = true
			}

			// this member is referenced as the "Len" field in another member.
			// By convention this field ends with a "Count"
			if mem.Name == m2.Len {
				// println("counter", cmd.Name, mem.Name)
				cmd.Mems[i].IsSliceCounter = true
				cmd.Mems[j].lenMems = append(cmd.Mems[j].lenMems, &cmd.Mems[i])
				if mem.Ptr == "*" {
					// counter is a pointer so that it can return the number
					// of elements when the array element is passed in as nil.
					// This requires calling the command twice, once to get
					// the array size, and the second call to fill the array.
					cmd.IsDoubleCall = true
				}
			}
		}
	}

	// println("generated command", gen.platform, cmd.Name)
	isCgo, isSys := true, false //
	switch {
	case gen.file == baseFile:
		gen.file = cgoFile
		gen.write(cmdSection, "") // init buffer
		writeCmd(cmd, isCgo, gen.out[cgoFile][cmdSection])
		gen.file = syscallFile
		gen.write(cmdSection, "") // init buffer
		writeCmd(cmd, isSys, gen.out[syscallFile][cmdSection])
		gen.file = baseFile
	case strings.Contains(gen.file, "win32"):
		gen.write(cmdSection, "") // init buffer
		writeCmd(cmd, isSys, gen.out[gen.file][cmdSection])
	default:
		gen.write(cmdSection, "") // init buffer
		writeCmd(cmd, isCgo, gen.out[gen.file][cmdSection])
	}
}

// Called once when starting generated code output.
// Start a new interface file
func (gen *generator) beginFile() {
	gen.file = baseFile

	// inject the handle type definitions
	s := defineSection
	gen.write(s, docLink("HANDLE", "VK_DEFINE_HANDLE")+"\n")
	gen.write(s, "type handle uintptr\n\n")
	gen.write(s, docLink("HANDLE", "VK_DEFINE_NON_DISPATCHABLE_HANDLE")+"\n")
	gen.write(s, "type nonDispatchableHandle uint64\n")

	// inject the bool translate methods used in commands,
	gen.write(s, "\n")
	gen.write(s, "// goBool32 is a type conversion function for special handling of Bool32 to bool.\n")
	gen.write(s, "func goBool32(val Bool32) bool { return val != Bool32(FALSE) }\n\n")
	gen.write(s, "// vkBool32 is a type conversion function for special handling of bool to Bool32.\n")
	gen.write(s, "func vkBool32(val bool) Bool32 {\n")
	gen.write(s, "	if val {\n")
	gen.write(s, "		return Bool32(TRUE)\n")
	gen.write(s, "	}\n")
	gen.write(s, "	return Bool32(FALSE)\n")
	gen.write(s, "}\n")
}

// Write interface for a feature and tag generated features as having been done.
func (gen *generator) beginFeature(feat *etree.Element, emit bool) {
	gen.feature = feat.SelectAttrValue("name", "")

	// different platforms need different files.
	gen.file = baseFile
	platform := feat.SelectAttrValue("platform", "")
	if platform != "" {
		gen.file = "vk_" + platform
	}
	slog.Debug("writing feature", "name", gen.feature, "file", gen.file)
}

// Finish an interface file, closing it when done.
func (gen *generator) endFeature() {
	gen.feature = ""
	gen.file = "vk"
}

// called once at the end of code generation.
func (gen *generator) endFile() {
	for filename, sections := range gen.out {
		content := strings.Builder{}

		// initialize the file based on platform.
		file := filepath.Join(bindingDir, filename+".go")

		// write the sections in order.
		for _, section := range sectionOrder {
			sectionContent := sections[section]
			if sectionContent == nil || sectionContent.Len() == 0 {
				continue // commands are generated later.
			}
			slog.Debug("writing section", "file", file, "name", section)
			if section != includeSection {
				content.WriteString(sectionBreak(section))
			}

			// end the enum const block.
			if section == enumSection {
				content.WriteString("\nconst (\n")
			}
			content.WriteString(sectionContent.String())
			if section == enumSection {
				content.WriteString(")\n")
			}
		}
		os.WriteFile(file, []byte(content.String()), 0644)
	}

	// format the output files.
	cmd := exec.Command("go", "fmt", "./vk")
	output, err := cmd.CombinedOutput()
	if err != nil {
		slog.Error("Error formatting files", "error", string(output))
	}
}

// write is a helper method to write strings to output buffers.
func (gen *generator) write(section, text string) {
	gen.out[gen.file][section].WriteString(text)
}

// sectionBreak returns a line comment for a section.
func sectionBreak(name string) string {
	pad := 70 - len(name)
	return fmt.Sprintf("\n// %s %s\n\n", name, strings.Repeat("=", pad))
}

// docLink returns a command that is a link to the Vulkan documentation.
func docLink(tag, name string) string {
	return fmt.Sprintf("// %s: https://docs.vulkan.org/refpages/latest/refpages/source/%s.html", tag, name)
}
